<a href="https://colab.research.google.com/github/anas1IA/SLT-GCN-PFA/blob/main/GNN_Dataset__ASL_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
!pip install rarfile

In [62]:
!pip  install torch_geometric

In [63]:
import torch
from torch.utils.data import TensorDataset
import rarfile
import os
from google.colab import files
from torch_geometric.loader import DataLoader

In [64]:
!git clone https://github.com/JamorMoussa/SLT-GCN-PFA.git

fatal: destination path 'SLT-GCN-PFA' already exists and is not an empty directory.


In [65]:
!mv SLT-GCN-PFA/asl_data/ asl_data

mv: cannot stat 'SLT-GCN-PFA/asl_data/': No such file or directory


In [66]:
# uploaded = files.upload()

In [67]:
# !mkdir train

In [68]:
# !mv asl_dataset.py train/


In [69]:
# !ls train/

In [70]:
# with rarfile.RarFile('dataset.rar', 'r') as rar_ref:
#     rar_ref.extractall('/content/train')

In [71]:
from asl_data.asl_dataset import ASLDataset

In [72]:
dataset = ASLDataset(root="/content/asl_data/dataset")

In [73]:
print(len(dataset))

19308


In [74]:
dataset[0].x

tensor([[0.2464, 0.8219],
        [0.3334, 0.7889],
        [0.4074, 0.6826],
        [0.4180, 0.5853],
        [0.4072, 0.5091],
        [0.3458, 0.5987],
        [0.3642, 0.5448],
        [0.3567, 0.6165],
        [0.3451, 0.6839],
        [0.2778, 0.6062],
        [0.2951, 0.5564],
        [0.2942, 0.6521],
        [0.2941, 0.7249],
        [0.2114, 0.6235],
        [0.2318, 0.5847],
        [0.2380, 0.6798],
        [0.2402, 0.7465],
        [0.1446, 0.6485],
        [0.1673, 0.6116],
        [0.1814, 0.6860],
        [0.1873, 0.7384]])

In [75]:
dataset.x.flatten()

tensor([0.2464, 0.8219, 0.3334,  ..., 0.2814, 0.3733, 0.2576])

In [76]:
dataset.y

tensor([ 6,  6,  6,  ..., 17, 17, 17])

In [77]:
X = []
y = []
for data in  dataset:
  X.append(data.x.flatten())
  y.append(data.y)

In [78]:
y

[tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tenso

In [79]:
X_train = torch.stack(X , dim =0)

In [80]:
X_train[0].shape

torch.Size([42])

In [81]:
X_train.shape

torch.Size([19308, 42])

In [82]:
y_train = torch.stack(y , dim = 0)

In [83]:
y_train


tensor([[ 6],
        [ 6],
        [ 6],
        ...,
        [17],
        [17],
        [17]])

In [84]:
y_train.shape

torch.Size([19308, 1])

In [85]:
y_train = y_train.t().squeeze(0)

In [86]:
y_train.shape

torch.Size([19308])

In [87]:
dataset_tensor = TensorDataset(X_train, y_train)

In [88]:
train_dataset = dataset_tensor[3000:]
test_dataset = dataset_tensor[:3000]

In [89]:
# for inputs, labels in zip(test_dataset[0], test_dataset[1]):
#     print("Labels:", labels)
#     print("Inputs:", inputs)


In [90]:
train_dataset

(tensor([[0.6296, 0.8513, 0.7212,  ..., 0.5058, 0.7231, 0.5339],
         [0.6113, 0.8805, 0.6972,  ..., 0.4966, 0.6944, 0.5255],
         [0.5202, 0.7911, 0.6134,  ..., 0.4256, 0.5958, 0.3849],
         ...,
         [0.5076, 0.9427, 0.5428,  ..., 0.8194, 0.2073, 0.7798],
         [0.4183, 0.6970, 0.3536,  ..., 0.5838, 0.2143, 0.5523],
         [0.5888, 0.3499, 0.5367,  ..., 0.2814, 0.3733, 0.2576]]),
 tensor([ 7,  7,  7,  ..., 17, 17, 17]))

In [91]:
train_loader = DataLoader(dataset_tensor, batch_size=64, shuffle=True)

In [92]:
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [93]:
# print(len(test_loader))

In [94]:
import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out




In [95]:
input_size = 42  # Assuming each input is of size 40
hidden_size = 64  # You can adjust this according to your data and requirements
num_classes = 28  # Number of output classes
model = MLP(input_size, hidden_size, num_classes)
num_epochs = 200

In [96]:
# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


In [97]:

def train(model, train_loader, criterion, optimizer):
    model.train()  # Set the model to training mode
    running_loss = 0.0
    correct = 0
    total = 0
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # Compute training accuracy
        _, predicted = torch.max(outputs.data, 1)
        # print(labels)
        # print(predicted)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        running_loss += loss.item()
    train_accuracy = correct / total

    return running_loss / len(train_loader), train_accuracy




In [98]:
# Training the model
for epoch in range(num_epochs):
    train_loss, train_accuracy = train(model, train_loader, criterion, optimizer)
    print(f'Epoch [{epoch+1}/{num_epochs}], Training Loss: {train_loss:.4f}, Training Accuracy: {train_accuracy:.4f}')

Epoch [1/200], Training Loss: 3.0188, Training Accuracy: 0.1456
Epoch [2/200], Training Loss: 2.6080, Training Accuracy: 0.2718
Epoch [3/200], Training Loss: 2.1467, Training Accuracy: 0.4027
Epoch [4/200], Training Loss: 1.8090, Training Accuracy: 0.4796
Epoch [5/200], Training Loss: 1.5636, Training Accuracy: 0.5563
Epoch [6/200], Training Loss: 1.3806, Training Accuracy: 0.6268
Epoch [7/200], Training Loss: 1.2428, Training Accuracy: 0.6707
Epoch [8/200], Training Loss: 1.1367, Training Accuracy: 0.7037
Epoch [9/200], Training Loss: 1.0556, Training Accuracy: 0.7238
Epoch [10/200], Training Loss: 0.9909, Training Accuracy: 0.7438
Epoch [11/200], Training Loss: 0.9353, Training Accuracy: 0.7584
Epoch [12/200], Training Loss: 0.8908, Training Accuracy: 0.7679
Epoch [13/200], Training Loss: 0.8506, Training Accuracy: 0.7816
Epoch [14/200], Training Loss: 0.8181, Training Accuracy: 0.7878
Epoch [15/200], Training Loss: 0.7879, Training Accuracy: 0.7968
Epoch [16/200], Training Loss: 0.7

In [99]:
def test(model, test_loader, criterion, device):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    test_loss = 0.0

    with torch.no_grad():
        for inputs, labels in zip(test_loader[0], test_loader[1]):

            # inputs, labels = inputs.to(device), labels.to(device)
            labels1 = labels.squeeze(0)
            outputs = model(inputs)
            loss = criterion(outputs, labels1)

            # Compute test loss
            test_loss += loss.item()
            # Compute test accuracy
            predicted = outputs.argmax()
            # print(labels1)
            correct += (predicted == labels1).sum().item()


    test_loss /= len(test_loader[1])
    test_accuracy = correct / len(test_dataset[1])

    return test_loss, test_accuracy


In [100]:
len(test_dataset[0])

3000

In [101]:
len(test_dataset[1])

3000

In [102]:
batch = next(iter(test_dataset))
print(len(batch))  # Should output 2

3000


In [103]:
test_loss, test_accuracy = test(model, test_dataset, criterion, device = 'cpu')
print(f'Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}')

Test Loss: 0.1559, Test Accuracy: 0.9637
